---
swagger: "2.0"
info:
  version: "2021-08-16T01:54:30Z"
  title: "GreetfromCountry"
host: "gwq9cmmrr8.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "nameofCountry"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:605060434181:function:HelloFromCountry/invocations"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"Country\": \"$input.params(\"nameofCountry\"))\"}"
        passthroughBehavior: "when_no_templates"
        cacheNamespace: "feyv5uo785"
        cacheKeyParameters:
        - "method.request.querystring.nameofCountry"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false