AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM and Swagger with created Lambda
Resources:
  HelloCountryAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      DefinitionUri: s3://sam-demo-mahe-101/1dc89aa42e5e96b2bac9afc93ca15db5
  samfunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloFromCountry
      Handler: hello_country.lambda_handler
      Runtime: python3.6
      CodeUri: s3://sam-demo-mahe-101/1bde524f43412eef9437d5b0893eff81
      Description: Sample SAM Lambda Deployment
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: HelloCountryAPI
            Path: /
            Method: GET
