AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test Pipeline Lambda
Resources:
  hellofunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello_country.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_function/hello_country.py
      Description: Sample SAM Lambda with Api event deployment
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
                Schedule: 'rate(1 minute)'